name: CI/CD for Google Cloud Kubernetes

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy to Google Cloud
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker images
        run: |
          # Use git SHA as tag for versioning
          IMAGE_TAG=${{ github.sha }}
          docker buildx build --push --tag ${{ secrets.DOCKER_USERNAME }}/nodeapp:${IMAGE_TAG} ./nodeapp
          docker buildx build --push --tag ${{ secrets.DOCKER_USERNAME }}/nodeapp2:${IMAGE_TAG} ./nodeapp2

          # Also tag as latest for convenience
          docker buildx build --push --tag ${{ secrets.DOCKER_USERNAME }}/nodeapp:latest ./nodeapp
          docker buildx build --push --tag ${{ secrets.DOCKER_USERNAME }}/nodeapp2:latest ./nodeapp2

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Install GKE gcloud auth plugin
        run: |
          gcloud components install gke-gcloud-auth-plugin
          echo "USE_GKE_GCLOUD_AUTH_PLUGIN=True" >> $GITHUB_ENV

      - name: Configure kubectl
        run: |
          gcloud container clusters get-credentials ${{ secrets.GKE_CLUSTER_NAME }} \
            --zone ${{ secrets.GCP_COMPUTE_ZONE }} \
            --project ${{ secrets.GCP_PROJECT_ID }}

      - name: Update deployment images and deploy
        run: |
          # Update the image tags in the deployment files
          IMAGE_TAG=${{ github.sha }}
          sed -i "s|sulkhan16/nodeapp:latest|${{ secrets.DOCKER_USERNAME }}/nodeapp:${IMAGE_TAG}|g" ./k8s/nodeapp-deployment.yaml
          sed -i "s|sulkhan16/nodeapp2:latest|${{ secrets.DOCKER_USERNAME }}/nodeapp2:${IMAGE_TAG}|g" ./k8s/nodeapp2-deployment.yaml

          # Apply the updated deployments
          kubectl apply -f ./k8s/
